### ISSUE TITLE
Spielbrett anlegen

### ISSUE THREAD

**Issue by AlexWirthAAU** [AlexWirthAAU/DieSiedlerVonCatan#1]
Das Spielbrett aus den einzelnen Hexagon-Feldern soll angelegt werden.
Unterteilt sich in die Issues #37 #35 #34 #36 #41

**Comment by klemensvo** [comment]
Hi Alex! Du hast mich auf meinem gmx-Account eingeladen. Lade mich bitte noch einmal auf meiner edu-Adresse ein: klemensvo@edu.aau.at

**Comment by ChrissiSenger** [comment]
- [ ] Eine Kreuzung muss seine Nachbar-Kreuzungen kennen

- [ ] Eine Kreuzung muss seine Nachbar-Straßen kennen

- [ ] Eine Kreuzung muss seine Nachbar-Landschaften kennen

- [ ] Eine Kreuzung muss seine Siedlung oder Stadt kennen

- [ ] Eine Kreuzung muss seinen Spieler kennen

- [ ] Eine Kreuzung muss seinen Hafen kennen

- [ ]  Eine Straße muss seine Nachbar-Kreuzungen kennen

- [ ] Eine Straße muss seine Nachbar-Straßen kennen

- [ ] Eine Straße muss seinen Spieler kennen
