### ISSUE TITLE
Entwicklungskarten Zusatz

### ISSUE THREAD

**Issue by ChrissiSenger** [AlexWirthAAU/DieSiedlerVonCatan#10]
- [ ] Es existiert je eine Zusatzkarte.
- [ ] Als Spieler   a.d.R. möchte ich, dass die Zusatzkarten nach dem Ausspielen aus dem Spiel   sind
- [ ] Als Spieler   a.d.R. möchte ich den Rückzug des Räubers ausspielen, damit der Räuber in die   Wüste versetzt wird
- [ ] Als Spieler   a.d.R. möchte ich die Ruhige See ausspielen, damit der Spieler mit den   meisten Siedlungen/Städten am Hafen einen Rohstoff aussuchen darf
- [ ] Als Spieler   a.d.R.möchte ich die Nachbarschaftshilfe ausspielen, damit der Spieler mit   den meisten Punkten, dem Spieler mit den wenigsten Punkten einen Rohstoff   abgibt
- [ ] Als Spieler   a.d.R. möchte ich das Gute Jahr ausspielen, damit alle Spieler einen Rohstoff   ihre Wal erhalten
- [ ] Als Spieler   a.d.R. möchte ich den Raubüberfall ausspielen, damit alle Spieler mit mehr   als 7 Rohstoffen 2 abgeben müssen und ich den Räuber versetzten darf
- [ ] Als Spieler   a.d.R. möchte ich das Ritterturnier ausspielen, damit der Spieler mit den   meisten Rittern einen Rohstoff seiner Wahl erhält
- [ ] Als Spieler   a.d.R. möchte ich den Handesvorteil ausspielen, damit der Spieler mit der   längsten Handeslstraße einen Rohstoff seiner Wahl erhält
- [ ] Als Spieler   a.d.R. möchte ich die Seuche ausspielen, damit alle Städte eine Runde lang   nur einen Rohstoff produzieren
- [ ] Als Spieler   a.d.R. möchte ich das Erdbeben ausspielen, damit alle anderen Spieler ein   Holz und einen Lehm zahlen müssen, um wieder bauen zu dürfen

**Comment by ChrissiSenger** [comment]
Gehören zum Catan-Kartenspiel und sind daher nicht notwendig
